import type { MarketRegion } from "@/lib/market/tickerIdentity";

export interface SwedishEquityUniverseEntry {
  ticker: string;
  companyName: string;
  exchange: MarketRegion;
  sector: string;
  marketCapBucket: "micro" | "small" | "mid" | "large";
  liquidityBucket: "thin" | "normal" | "liquid";
  verified: boolean;
}

const VERIFIED_SWEDISH_UNIVERSE: SwedishEquityUniverseEntry[] = [
  { ticker: "EPIS B", companyName: "Episurf Medical AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "HOIST", companyName: "Hoist Finance AB", exchange: "Sweden", sector: "financials", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "BIOA", companyName: "BioArctic AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "TOBII", companyName: "Tobii AB", exchange: "Sweden", sector: "tech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "SINCH", companyName: "Sinch AB", exchange: "Sweden", sector: "software", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "YUBICO", companyName: "Yubico AB", exchange: "First North", sector: "cyber security", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "ASTOR", companyName: "Astor Group AB", exchange: "Spotlight", sector: "defense", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "SIVE", companyName: "Sivers Semiconductors AB", exchange: "Sweden", sector: "semiconductors", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "ADVE", companyName: "Advenica AB", exchange: "Sweden", sector: "cyber security", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "ADVBOX", companyName: "Adventure Box Technology AB", exchange: "First North", sector: "gaming", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "AAC", companyName: "AAC Clyde Space AB", exchange: "First North", sector: "space", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "SHT", companyName: "Smart High Tech AB", exchange: "Spotlight", sector: "industrial tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "KVIX", companyName: "Kvix AB", exchange: "Nordic SME", sector: "software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "SBB B", companyName: "Samhallsbyggnadsbolaget i Norden AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "BERG B", companyName: "Bergman & Beving AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "CI B", companyName: "Cint Group AB", exchange: "Sweden", sector: "software", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "NCC", companyName: "NCC AB", exchange: "Sweden", sector: "construction", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "MOFAST", companyName: "Mofast AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "ELECTROLUX", companyName: "AB Electrolux", exchange: "Sweden", sector: "consumer", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "MANGOLD", companyName: "Mangold AB", exchange: "Sweden", sector: "financials", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "NORDNET", companyName: "Nordnet AB", exchange: "Sweden", sector: "financials", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "LOGISTEA", companyName: "Logistea AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "NORDREST", companyName: "Nordrest Holding AB", exchange: "First North", sector: "consumer", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "MEDI", companyName: "Medivir AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "XSPRAY", companyName: "Xspray Pharma AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "CANTA", companyName: "Cantargia AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "VICO", companyName: "Vicore Pharma Holding AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "IMMU", companyName: "Immunovia AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "BICO", companyName: "BICO Group AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "small", liquidityBucket: "liquid", verified: true },
  { ticker: "CAMX", companyName: "Camurus AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "VITR", companyName: "Vitrolife AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "IRLAB A", companyName: "IRLAB Therapeutics AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "HNSA", companyName: "Hansa Biopharma AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "SAAB B", companyName: "Saab AB", exchange: "Sweden", sector: "defense", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "MILDEF", companyName: "MilDef Group AB", exchange: "Sweden", sector: "defense", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "CLAV", companyName: "Clavister Holding AB", exchange: "First North", sector: "cyber security", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "GOMX", companyName: "GomSpace Group AB", exchange: "First North", sector: "space", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "NCAB", companyName: "NCAB Group AB", exchange: "Sweden", sector: "semiconductors", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "MYCR", companyName: "Mycronic AB", exchange: "Sweden", sector: "semiconductors", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "HEXATRONIC", companyName: "Hexatronic Group AB", exchange: "Sweden", sector: "datacenter", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "VIMIAN", companyName: "Vimian Group AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "EMBRAC B", companyName: "Embracer Group AB", exchange: "Sweden", sector: "gaming", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "G5EN", companyName: "G5 Entertainment AB", exchange: "Sweden", sector: "gaming", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "VNV", companyName: "VNV Global AB", exchange: "Sweden", sector: "turnaround", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "KIND SDB", companyName: "Kindred Group plc", exchange: "Sweden", sector: "gaming", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "ALIG", companyName: "Alleima AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "ARJO B", companyName: "Arjo AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "BEIJ B", companyName: "Beijer Ref AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "BILI A", companyName: "Bilia AB", exchange: "Sweden", sector: "consumer", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "BOL", companyName: "Boliden AB", exchange: "Sweden", sector: "metals", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "BONAV B", companyName: "Bonava AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "BURE", companyName: "Bure Equity AB", exchange: "Sweden", sector: "investment", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "CAST", companyName: "Castellum AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "COOR", companyName: "Coor Service Management Holding AB", exchange: "Sweden", sector: "services", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "DORO", companyName: "Doro AB", exchange: "Sweden", sector: "consumer tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "ELAN B", companyName: "Elanders AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "ELTEL", companyName: "Eltel AB", exchange: "Sweden", sector: "infrastructure", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "EOLU B", companyName: "Eolus Vind AB", exchange: "Sweden", sector: "energy", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "FABG", companyName: "Fabege AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "HMS", companyName: "HMS Networks AB", exchange: "Sweden", sector: "industrial tech", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "INSTAL", companyName: "Instalco AB", exchange: "Sweden", sector: "construction services", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "LAGR B", companyName: "Lagercrantz Group AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "LIME", companyName: "Lime Technologies AB", exchange: "Sweden", sector: "software", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "MIPS", companyName: "Mips AB", exchange: "Sweden", sector: "consumer", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "NIBE B", companyName: "Nibe Industrier AB", exchange: "Sweden", sector: "energy tech", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "NOLA B", companyName: "Nolato AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "OEM B", companyName: "OEM International AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "PACT", companyName: "Proact IT Group AB", exchange: "Sweden", sector: "IT services", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "PLAZ B", companyName: "Platzer Fastigheter Holding AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "PROB", companyName: "Probi AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "RAY B", companyName: "RaySearch Laboratories AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "SAGA B", companyName: "Sagax AB", exchange: "Sweden", sector: "real estate", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "SECT B", companyName: "Sectra AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "SOBI", companyName: "Swedish Orphan Biovitrum AB", exchange: "Sweden", sector: "biotech", marketCapBucket: "large", liquidityBucket: "liquid", verified: true },
  { ticker: "TROAX", companyName: "Troax Group AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "VBG B", companyName: "VBG Group AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "VIT B", companyName: "Vitec Software Group AB", exchange: "Sweden", sector: "software", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "XANO B", companyName: "Xano Industri AB", exchange: "Sweden", sector: "industrials", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "XVIVO", companyName: "Xvivo Perfusion AB", exchange: "Sweden", sector: "medtech", marketCapBucket: "mid", liquidityBucket: "normal", verified: true },
  { ticker: "AERO", companyName: "Aerowash AB", exchange: "Spotlight", sector: "industrials", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "ANOT", companyName: "Anoto Group AB", exchange: "Spotlight", sector: "tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "APTR", companyName: "Appspotr AB", exchange: "Spotlight", sector: "software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "AVT B", companyName: "AVTECH Sweden AB", exchange: "Spotlight", sector: "aviation tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "BPC", companyName: "Bioprocess Control AB", exchange: "Spotlight", sector: "industrial tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "CLEM", companyName: "Clemondo Group AB", exchange: "Spotlight", sector: "consumer", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "ENERS", companyName: "Enersize Oyj", exchange: "Spotlight", sector: "energy tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "HILB B", companyName: "Hilbert Group AB", exchange: "First North", sector: "fintech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "KAV", companyName: "Katalysen Ventures AB", exchange: "Spotlight", sector: "investment", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "NFO", companyName: "NFO Drives AB", exchange: "Spotlight", sector: "industrial tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "NOSA", companyName: "Nosa Plugs AB", exchange: "Spotlight", sector: "medtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "ODI", companyName: "Odinwell AB", exchange: "Spotlight", sector: "medtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "QBNK", companyName: "QBNK Holding AB", exchange: "Spotlight", sector: "software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "RLOS", companyName: "Raytelligence AB", exchange: "Spotlight", sector: "medtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "SOFTX", companyName: "Softronic AB", exchange: "Spotlight", sector: "IT services", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "TURA", companyName: "Tura Group AB", exchange: "Spotlight", sector: "consumer", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "VO2", companyName: "VO2 Cap Holding AB", exchange: "Spotlight", sector: "media tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "AWRD", companyName: "Awardit AB", exchange: "First North", sector: "consumer tech", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "BOUL", companyName: "Boule Diagnostics AB", exchange: "First North", sector: "medtech", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "CELLINK", companyName: "Cellink AB", exchange: "First North", sector: "biotech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "DUG", companyName: "Dug Foodtech AB", exchange: "First North", sector: "foodtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "EGTX", companyName: "Enigio Time AB", exchange: "First North", sector: "fintech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "FING B", companyName: "Fingerprint Cards AB", exchange: "First North", sector: "semiconductors", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "GENI", companyName: "Genovis AB", exchange: "First North", sector: "biotech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "GIGSEK", companyName: "Gaming Innovation Group Inc.", exchange: "First North", sector: "gaming", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "IMINT", companyName: "IMINT Image Intelligence AB", exchange: "First North", sector: "software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "MAGI", companyName: "MAG Interactive AB", exchange: "First North", sector: "gaming", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "MVIR B", companyName: "Mentice AB", exchange: "First North", sector: "medtech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "NANEXA", companyName: "Nanexa AB", exchange: "First North", sector: "biotech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "PLEJD", companyName: "Plejd AB", exchange: "First North", sector: "industrial tech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "QLINEA", companyName: "Q-linea AB", exchange: "First North", sector: "medtech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "REJL B", companyName: "Rejlers AB", exchange: "First North", sector: "consulting", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "SAVR", companyName: "SAVR AB", exchange: "First North", sector: "fintech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "SEDANA", companyName: "Sedana Medical AB", exchange: "First North", sector: "medtech", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "TRUE B", companyName: "Truecaller AB", exchange: "First North", sector: "software", marketCapBucket: "mid", liquidityBucket: "liquid", verified: true },
  { ticker: "VPLAY B", companyName: "Viaplay Group AB", exchange: "First North", sector: "media", marketCapBucket: "small", liquidityBucket: "normal", verified: true },
  { ticker: "ZICC", companyName: "Ziccum AB", exchange: "First North", sector: "biotech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "ACRI A", companyName: "Acrinova AB", exchange: "Nordic SME", sector: "real estate", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "BIM", companyName: "BIMobject AB", exchange: "Nordic SME", sector: "software", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "BRIGHT", companyName: "BrightBid Group AB", exchange: "Nordic SME", sector: "adtech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "CSEC", companyName: "C Security Systems AB", exchange: "Nordic SME", sector: "security tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "DIVIO B", companyName: "Divio Technologies AB", exchange: "Nordic SME", sector: "cloud software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "FREJA", companyName: "Freja eID Group AB", exchange: "Nordic SME", sector: "cyber security", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "HEART", companyName: "Heart Aerospace AB", exchange: "Nordic SME", sector: "aviation tech", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "KILI", companyName: "Kiliaro Group AB", exchange: "Nordic SME", sector: "software", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "MAVEN", companyName: "Maven Wireless Sweden AB", exchange: "Nordic SME", sector: "telecom tech", marketCapBucket: "small", liquidityBucket: "thin", verified: true },
  { ticker: "NEXAM", companyName: "Nexam Chemical Holding AB", exchange: "Nordic SME", sector: "materials", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
  { ticker: "WYLD", companyName: "Wyld Networks AB", exchange: "Nordic SME", sector: "IoT", marketCapBucket: "micro", liquidityBucket: "thin", verified: true },
];

export function getSwedishEquityUniverse() {
  const configured = (process.env.SWEDISH_EQUITY_UNIVERSE ?? "")
    .split(",")
    .map((ticker) => ticker.trim().toUpperCase())
    .filter(Boolean);
  const configuredEntries = configured.map((ticker): SwedishEquityUniverseEntry => ({
    ticker,
    companyName: ticker,
    exchange: "Sweden",
    sector: "unknown",
    marketCapBucket: "small",
    liquidityBucket: "normal",
    verified: true,
  }));

  const map = new Map<string, SwedishEquityUniverseEntry>();
  [...VERIFIED_SWEDISH_UNIVERSE, ...configuredEntries].forEach((entry) => map.set(entry.ticker, entry));
  return [...map.values()];
}
